/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NeuralNet;

import java.awt.FileDialog;


/**
 *
 * @author faiva78
 */
public class ManagerForm extends javax.swing.JFrame {

    private int epoch = 0;
    private boolean runSimFlag = true;
    public String fileLocation;
    public String extNet = ".net";
    public String extCsv = ".csv";
    public String dir = System.getProperty("user.home");
    public String file = "TestNet0";

    /**
     * Creates new form ManagerForm
     */
    public ManagerForm() {
        initComponents();
        buttonGroup1.add(jRadioButtonBackprop);
        buttonGroup1.add(jRadioButtonAnnealing);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        data = new NeuralNet.Data();
        net = new NeuralNet.Net();
        func = new NeuralNet.Func();
        timer = new NeuralNet.Timer();
        backProp = new NeuralNet.BackPropagation();
        buttonGroup1 = new javax.swing.ButtonGroup();
        annealing = new NeuralNet.Annealing();
        tableDataModel1 = new NeuralNet.TableDataModel();
        jPanelData = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonDataSave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonAddSample = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelFunctionGenerator = new javax.swing.JPanel();
        jTextFieldFormula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSamples = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jFunctionPanel1 = new NeuralNet.JFunctionPanel();
        jPanelTrainParameters = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jTextTimerDelay = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTexEpochs = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextErrorTrackLenght = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextMinimumError = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabelErrorRms = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelDError = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelDErrorRms = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButtonStop = new javax.swing.JButton();
        jButtonStart = new javax.swing.JButton();
        jPanelTopology = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButtonAddNeuron1 = new javax.swing.JButton();
        jButtonAddLayer = new javax.swing.JButton();
        jButtonAddNeuron = new javax.swing.JButton();
        jButtonRemoveLayer = new javax.swing.JButton();
        jTextAddNeuronLayer = new javax.swing.JTextField();
        jpanelNeuron1 = new NeuralNet.JpanelNeuron();
        jToolBar2 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();
        jButtonLoadNet = new javax.swing.JButton();
        jButtonSaveNEt = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonCreateNet = new javax.swing.JButton();
        jTexTopology = new javax.swing.JTextField();
        jPanelAlgorythms = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFeedRandom = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSliderFeddRandom = new javax.swing.JSlider();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2BackProp = new javax.swing.JPanel();
        jRadioButtonBackprop = new javax.swing.JRadioButton();
        jSliderETA = new javax.swing.JSlider();
        jSliderMOMENTUM = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTexETA = new javax.swing.JTextField();
        jTextMomentum = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jSliderErrorCorrection = new javax.swing.JSlider();
        jLabelErrorCorrection = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jCheckBoxShuffle = new javax.swing.JCheckBox();
        jCheckBoxRandom = new javax.swing.JCheckBox();
        jPanelAnnealing = new javax.swing.JPanel();
        jRadioButtonAnnealing = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSliderAnnStart = new javax.swing.JSlider();
        jSliderAnnStop = new javax.swing.JSlider();
        jSliderAnnCycles = new javax.swing.JSlider();
        jTextAnnStart = new javax.swing.JTextField();
        jTextAnnStop = new javax.swing.JTextField();
        jTextAnnCycles = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTrainHistoryPanel1 = new NeuralNet.JTrainHistoryPanel();
        jPanel2 = new javax.swing.JPanel();
        jDataPanel1 = new NeuralNet.JDataPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelData.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data"));

        jToolBar1.setRollover(true);

        jButtonDataSave.setText("Save");
        jButtonDataSave.setFocusable(false);
        jButtonDataSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDataSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDataSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDataSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonDataSave);

        jButton2.setText("Function");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateDataActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButtonAddSample.setText("Add Sample");
        jButtonAddSample.setEnabled(false);
        jButtonAddSample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSampleActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAddSample);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane2.addTab("Data", jScrollPane1);

        jTextFieldFormula.setText("(sin((2*x)*3.1416)+1)/2");

        jLabel2.setText("Samples");

        jTextFieldSamples.setText("30");

        jButton1.setText("test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestFuncActionPerformed(evt);
            }
        });

        jFunctionPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jFunctionPanel1Layout = new javax.swing.GroupLayout(jFunctionPanel1);
        jFunctionPanel1.setLayout(jFunctionPanel1Layout);
        jFunctionPanel1Layout.setHorizontalGroup(
            jFunctionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jFunctionPanel1Layout.setVerticalGroup(
            jFunctionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelFunctionGeneratorLayout = new javax.swing.GroupLayout(jPanelFunctionGenerator);
        jPanelFunctionGenerator.setLayout(jPanelFunctionGeneratorLayout);
        jPanelFunctionGeneratorLayout.setHorizontalGroup(
            jPanelFunctionGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFunctionGeneratorLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldSamples, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addComponent(jFunctionPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextFieldFormula, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelFunctionGeneratorLayout.setVerticalGroup(
            jPanelFunctionGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFunctionGeneratorLayout.createSequentialGroup()
                .addComponent(jTextFieldFormula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFunctionGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldSamples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFunctionPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Function", jPanelFunctionGenerator);

        javax.swing.GroupLayout jPanelDataLayout = new javax.swing.GroupLayout(jPanelData);
        jPanelData.setLayout(jPanelDataLayout);
        jPanelDataLayout.setHorizontalGroup(
            jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanelDataLayout.setVerticalGroup(
            jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
        );

        jPanelTrainParameters.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Simulation"));

        jTextTimerDelay.setText("50");

        jLabel4.setText("Delay (ms)");

        jTexEpochs.setText("25000");

        jLabel6.setText("Min Error");

        jLabel7.setText("Rms Len");

        jTextErrorTrackLenght.setText("1000");

        jLabel3.setText("Epochs");

        jTextMinimumError.setText("0.01");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextMinimumError, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTexEpochs, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextTimerDelay, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextErrorTrackLenght, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTexEpochs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextTimerDelay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextMinimumError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextErrorTrackLenght, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Parameters", jPanel7);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setText("Error rms");

        jLabelErrorRms.setText("0");
        jLabelErrorRms.setMaximumSize(new java.awt.Dimension(6, 140));
        jLabelErrorRms.setPreferredSize(new java.awt.Dimension(36, 14));

        jLabelError.setText("0");
        jLabelError.setMaximumSize(new java.awt.Dimension(6, 140));
        jLabelError.setPreferredSize(new java.awt.Dimension(36, 14));

        jLabel15.setText("Error");

        jLabelDError.setText("0");
        jLabelDError.setMaximumSize(new java.awt.Dimension(6, 140));
        jLabelDError.setPreferredSize(new java.awt.Dimension(36, 14));

        jLabel16.setText("void");

        jLabel17.setText("d Error rms");

        jLabelDErrorRms.setText("0");
        jLabelDErrorRms.setMaximumSize(new java.awt.Dimension(6, 140));
        jLabelDErrorRms.setPreferredSize(new java.awt.Dimension(36, 14));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabelErrorRms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabelDError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabelDErrorRms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabelErrorRms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabelDErrorRms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabelDError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Output", jPanel5);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new java.awt.GridLayout());

        jButtonStop.setText("Stop");
        jButtonStop.setEnabled(false);
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonStop);

        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonStart);

        javax.swing.GroupLayout jPanelTrainParametersLayout = new javax.swing.GroupLayout(jPanelTrainParameters);
        jPanelTrainParameters.setLayout(jPanelTrainParametersLayout);
        jPanelTrainParametersLayout.setHorizontalGroup(
            jPanelTrainParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelTrainParametersLayout.setVerticalGroup(
            jPanelTrainParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrainParametersLayout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelTopology.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Net"));

        jButtonAddNeuron1.setText("Remove");
        jButtonAddNeuron1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNeuron1ActionPerformed(evt);
            }
        });

        jButtonAddLayer.setText("Add Layer");
        jButtonAddLayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddLayerActionPerformed(evt);
            }
        });

        jButtonAddNeuron.setText("Add Neuron");
        jButtonAddNeuron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNeuronActionPerformed(evt);
            }
        });

        jButtonRemoveLayer.setText("Remove");
        jButtonRemoveLayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveLayerActionPerformed(evt);
            }
        });

        jTextAddNeuronLayer.setText("0");

        jpanelNeuron1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpanelNeuron1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpanelNeuron1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpanelNeuron1Layout = new javax.swing.GroupLayout(jpanelNeuron1);
        jpanelNeuron1.setLayout(jpanelNeuron1Layout);
        jpanelNeuron1Layout.setHorizontalGroup(
            jpanelNeuron1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpanelNeuron1Layout.setVerticalGroup(
            jpanelNeuron1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButtonAddLayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAddNeuron)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButtonRemoveLayer, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAddNeuron1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addComponent(jpanelNeuron1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextAddNeuronLayer)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddLayer)
                    .addComponent(jButtonAddNeuron))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRemoveLayer)
                    .addComponent(jButtonAddNeuron1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextAddNeuronLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelNeuron1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar2.setRollover(true);

        jButton4.setText("Empty");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton4);

        jButtonLoadNet.setText("Load");
        jButtonLoadNet.setFocusable(false);
        jButtonLoadNet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLoadNet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonLoadNet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadNetActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonLoadNet);

        jButtonSaveNEt.setText("Save");
        jButtonSaveNEt.setFocusable(false);
        jButtonSaveNEt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSaveNEt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSaveNEt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveNEtActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonSaveNEt);
        jToolBar2.add(jSeparator1);

        jButtonCreateNet.setText("New");
        jButtonCreateNet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateNetActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonCreateNet);

        jTexTopology.setText("1,7,1");
        jToolBar2.add(jTexTopology);

        javax.swing.GroupLayout jPanelTopologyLayout = new javax.swing.GroupLayout(jPanelTopology);
        jPanelTopology.setLayout(jPanelTopologyLayout);
        jPanelTopologyLayout.setHorizontalGroup(
            jPanelTopologyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelTopologyLayout.setVerticalGroup(
            jPanelTopologyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopologyLayout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelAlgorythms.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Training algorythm parameters"));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Feed forward");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSliderFeddRandom, org.jdesktop.beansbinding.ELProperty.create("${(value*value)/10000}"), jTextFeedRandom, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel14.setText("Random");

        jSliderFeddRandom.setValue(0);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFeedRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSliderFeddRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFeedRandom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addComponent(jSliderFeddRandom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2BackProp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jRadioButtonBackprop.setSelected(true);
        jRadioButtonBackprop.setText("Backpropagation");
        jRadioButtonBackprop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBackpropActionPerformed(evt);
            }
        });

        jSliderETA.setValue(23);

        jSliderMOMENTUM.setValue(8);

        jLabel9.setText("Momentum");

        jLabel8.setText("ETA");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSliderETA, org.jdesktop.beansbinding.ELProperty.create("${(value*value)/500}"), jTexETA, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSliderMOMENTUM, org.jdesktop.beansbinding.ELProperty.create("${(value*value)/500}"), jTextMomentum, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSliderErrorCorrection.setValue(0);

        jLabelErrorCorrection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSliderErrorCorrection, org.jdesktop.beansbinding.ELProperty.create("${value/100}"), jLabelErrorCorrection, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel18.setLabelFor(jSliderErrorCorrection);
        jLabel18.setText("<html> Error <br>Correction");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErrorCorrection, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderErrorCorrection, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelErrorCorrection)
                        .addComponent(jSliderErrorCorrection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jCheckBoxShuffle.setText("Shuffle");

        jCheckBoxRandom.setText("Random");

        javax.swing.GroupLayout jPanel2BackPropLayout = new javax.swing.GroupLayout(jPanel2BackProp);
        jPanel2BackProp.setLayout(jPanel2BackPropLayout);
        jPanel2BackPropLayout.setHorizontalGroup(
            jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2BackPropLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2BackPropLayout.createSequentialGroup()
                        .addGroup(jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2BackPropLayout.createSequentialGroup()
                                .addComponent(jCheckBoxShuffle, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBoxRandom))
                            .addGroup(jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2BackPropLayout.createSequentialGroup()
                                    .addGroup(jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2BackPropLayout.createSequentialGroup()
                                            .addComponent(jTexETA, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jSliderETA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2BackPropLayout.createSequentialGroup()
                                            .addComponent(jTextMomentum, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jSliderMOMENTUM, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                                .addComponent(jRadioButtonBackprop)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2BackPropLayout.setVerticalGroup(
            jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2BackPropLayout.createSequentialGroup()
                .addComponent(jRadioButtonBackprop, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTexETA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(jSliderETA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextMomentum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(jSliderMOMENTUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxShuffle)
                    .addComponent(jCheckBoxRandom))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Backpropagation", jPanel2BackProp);

        jPanelAnnealing.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jRadioButtonAnnealing.setText("Annealing");

        jLabel10.setText("Stop");

        jLabel11.setText("Start");

        jLabel12.setText("Cycles");

        jSliderAnnStart.setValue(100);

        jSliderAnnStop.setValue(1);

        jSliderAnnCycles.setValue(30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSliderAnnStart, org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextAnnStart, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSliderAnnStop, org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextAnnStop, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSliderAnnCycles, org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextAnnCycles, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanelAnnealingLayout = new javax.swing.GroupLayout(jPanelAnnealing);
        jPanelAnnealing.setLayout(jPanelAnnealingLayout);
        jPanelAnnealingLayout.setHorizontalGroup(
            jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnnealingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextAnnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextAnnCycles, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextAnnStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSliderAnnStop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jSliderAnnCycles, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSliderAnnStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelAnnealingLayout.createSequentialGroup()
                .addComponent(jRadioButtonAnnealing)
                .addGap(0, 257, Short.MAX_VALUE))
        );
        jPanelAnnealingLayout.setVerticalGroup(
            jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnnealingLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderAnnCycles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAnnealingLayout.createSequentialGroup()
                        .addComponent(jRadioButtonAnnealing, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAnnealingLayout.createSequentialGroup()
                                .addGroup(jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextAnnStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextAnnStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelAnnealingLayout.createSequentialGroup()
                                .addComponent(jSliderAnnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSliderAnnStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextAnnCycles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Annealing", jPanelAnnealing);

        javax.swing.GroupLayout jPanelAlgorythmsLayout = new javax.swing.GroupLayout(jPanelAlgorythms);
        jPanelAlgorythms.setLayout(jPanelAlgorythmsLayout);
        jPanelAlgorythmsLayout.setHorizontalGroup(
            jPanelAlgorythmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlgorythmsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlgorythmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        jPanelAlgorythmsLayout.setVerticalGroup(
            jPanelAlgorythmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlgorythmsLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "History"));

        javax.swing.GroupLayout jTrainHistoryPanel1Layout = new javax.swing.GroupLayout(jTrainHistoryPanel1);
        jTrainHistoryPanel1.setLayout(jTrainHistoryPanel1Layout);
        jTrainHistoryPanel1Layout.setHorizontalGroup(
            jTrainHistoryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );
        jTrainHistoryPanel1Layout.setVerticalGroup(
            jTrainHistoryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTrainHistoryPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTrainHistoryPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data "));

        jDataPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jDataPanel1Layout = new javax.swing.GroupLayout(jDataPanel1);
        jDataPanel1.setLayout(jDataPanel1Layout);
        jDataPanel1Layout.setHorizontalGroup(
            jDataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDataPanel1Layout.setVerticalGroup(
            jDataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDataPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDataPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelTopology, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAlgorythms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelTrainParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelTrainParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelTopology, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelAlgorythms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTestFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestFuncActionPerformed
        // Paint function:
        func = new Func(jTextFieldFormula.getText());
        int steps = Integer.valueOf(jTextFieldSamples.getText());
        jFunctionPanel1.func = func;
        jFunctionPanel1.steps = steps;
        jFunctionPanel1.repaint();
    }//GEN-LAST:event_jButtonTestFuncActionPerformed

    private void jButtonCreateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateDataActionPerformed
        // XXX Create table: finish table<->fata management

        data = new Data();
        func = new Func(jTextFieldFormula.getText());
        double steps = 1 / (Double.valueOf(jTextFieldSamples.getText()) - 1);

        Uti.DataFunc1P(func, 0, 1, steps, data);

        TableDataModel tableDataModel = new TableDataModel(data);
        jTable1.setModel(tableDataModel);

    }//GEN-LAST:event_jButtonCreateDataActionPerformed

    private void jButtonCreateNetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateNetActionPerformed
        // TODO Create a New Net from topology: add function activation selection in a new tab
        net = new Net();
        net.createNet(jTexTopology.getText());
        jpanelNeuron1.net = net;
        jpanelNeuron1.repaint();
    }//GEN-LAST:event_jButtonCreateNetActionPerformed

    private void updateLabels() {
        // update the data output visualization
        String format ="%.4f";
        jLabelErrorRms.setText(String.format(format, data.errorTrack.mean()));
        jLabelDErrorRms.setText(String.format(format, data.errorTrack.meanDer()));
        jLabelError.setText(String.format(format, data.getDataError()));
    }

    private void updateTrain() {
        // set backprop parameters
        try {

            backProp.ETA = Uti.jTextToDouble(jTexETA);
            backProp.MOMENTUM = Uti.jTextToDouble(jTextMomentum);
            backProp.dataModifier.randomInput = Uti.jTextToDouble(jTextFeedRandom);

            //backPropagation.dataModifier.dataErrorCorrection = jCheckBoxErrorCorrection.isSelected();
            backProp.dataModifier.dataRandomize = jCheckBoxRandom.isSelected();
            backProp.dataModifier.dataShuffle = jCheckBoxShuffle.isSelected();
            backProp.dataModifier.errorRatioCorrection = Uti.jLabelToDouble(jLabelErrorCorrection);

            //annealing.start;
            annealing.start = Uti.jTextToDouble(jTextAnnStart);
            annealing.stop = Uti.jTextToDouble(jTextAnnStop);
            annealing.cycles = Uti.jTextToDouble(jTextAnnCycles);
            annealing.dataModifier.randomInput = Uti.jTextToDouble(jTextFeedRandom);

        } catch (Exception e) {
            Error ee = new Error("Error in sliders method:" + e.getMessage());
            System.out.println((ee.getMessage()));
        }

    }


    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        // TODO Gen Algo
        //
        Thread RunSim = new Thread(new Runnable() {

            @Override
            public void run() {
                try {

                    //set up buttons visibility
                    jButtonStop.setEnabled(true);
                    jButtonStart.setEnabled(false);

                    // set timer
                    timer.setTimeOut(Long.valueOf(jTextTimerDelay.getText()));

                    // set tracking error lenght
                    data.errorTrack.lenght = Integer.valueOf(jTextErrorTrackLenght.getText());

                    // set the History panel parameters
                    jTrainHistoryPanel1.minimumError = Double.valueOf(jTextMinimumError.getText());
                    jTrainHistoryPanel1.totalEpoch = Integer.valueOf(jTexEpochs.getText());
                    jTrainHistoryPanel1.data = data;
                    jTrainHistoryPanel1.clear();

                    //set the data panel
                    jDataPanel1.data = data;

                    updateTrain();

                    // set sto flag
                    runSimFlag = true;

                    // reset eèpoch
                    epoch = 0;

                    while (runSimFlag) {

                        while (epoch < Long.valueOf(jTexEpochs.getText())) {

                            //increase epoch
                            epoch++;

                            //train 
                            if (jRadioButtonBackprop.isSelected()) {
                                //use backprop
                                backProp.train(net, data);
                            } else if (jRadioButtonAnnealing.isSelected()) {
                                //use annealing
                                annealing.train(net, data);
                            }

                            // record error
                            data.errorTrack.add(data.getDataError());

                            // if timer
                            if (timer.check()) {
                                updateLabels();

                                //update and paint panels
                                //
                                jTrainHistoryPanel1.epoch = epoch;
                                jTrainHistoryPanel1.repaint();
                                jDataPanel1.repaint();

                                updateTrain();

                                // reset timer
                                timer.reset();

                            }

                            // if solution found
                            boolean err = (data.errorTrack.mean() < Double.valueOf(jTextMinimumError.getText()));
                            if (err) {
                                runSimFlag = false;

                            }

                            //if end of sim
                            if (!runSimFlag) {
                                jButtonStop.setEnabled(false);
                                jButtonStart.setEnabled(true);
                                System.out.println("finished ");
                                break;
                            }

                        }
                        //clear and reset epoch 
                        epoch = 0;

                        jTrainHistoryPanel1.clear();

                    }

                } catch (Exception e) {

                    jButtonStop.setEnabled(false);
                    jButtonStart.setEnabled(true);
                    runSimFlag = false;
                    throw new Error("Error in backprop:" + e.getMessage());
                }

            }
        });
        //start te thread
        RunSim.start();

    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
        jButtonStop.setEnabled(false);
        jButtonStart.setEnabled(true);
        runSimFlag = false;
    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jButtonLoadNetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadNetActionPerformed
        FileDialog fd = new FileDialog(this, "Load a net", FileDialog.LOAD);
        fd.setDirectory(dir);
        fd.setFile("*.net");
        fd.setVisible(true);
        String filename = fd.getFile();
        if (filename != null) {
            net = new Net();
            Uti.loadNet(dir + "/" + filename, net);
        }
    }//GEN-LAST:event_jButtonLoadNetActionPerformed

    private void jButtonSaveNEtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveNEtActionPerformed
        FileDialog fd = new FileDialog(this, "Save a net", FileDialog.SAVE);
        fd.setDirectory(dir);
        fd.setFile("*.net");
        fd.setVisible(true);
        String filename = fd.getFile();
        if (filename != null) {
            Uti.saveNet(dir + "/" + filename + extNet, net);
        }
    }//GEN-LAST:event_jButtonSaveNEtActionPerformed

    private void jButtonDataSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDataSaveActionPerformed
        // TODO fix file extension bug

        FileDialog fd = new FileDialog(this, "Save net data", FileDialog.SAVE);
        fd.setDirectory(dir);
        fd.setFile("*.csv");
        fd.setVisible(true);
        String filename = fd.getFile();
        if (filename != null) {
            Uti.saveDataCSV(net, data, dir + "/" + filename + extCsv);
        }
    }//GEN-LAST:event_jButtonDataSaveActionPerformed

    private void jRadioButtonBackpropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBackpropActionPerformed
    }//GEN-LAST:event_jRadioButtonBackpropActionPerformed

    private void jButtonAddSampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSampleActionPerformed
        data.addSample(new double[]{0}, new double[]{0});
        tableDataModel1.fireTableDataChanged();
        jTable1.repaint();
    }//GEN-LAST:event_jButtonAddSampleActionPerformed

    private void jButtonAddLayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddLayerActionPerformed
        net.addLayer();
        jpanelNeuron1.first=true;
        jpanelNeuron1.repaint();
    }//GEN-LAST:event_jButtonAddLayerActionPerformed

    private void jButtonAddNeuronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNeuronActionPerformed
        net.addNeuron(net.LayerList.get(Integer.valueOf(jTextAddNeuronLayer.getText())), 1);
        jpanelNeuron1.first=true;
        jpanelNeuron1.repaint();

    }//GEN-LAST:event_jButtonAddNeuronActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        net = new Net();
        net.createNet("0");
        jpanelNeuron1.net = net;
        jpanelNeuron1.first=true;
        jpanelNeuron1.repaint();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonRemoveLayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveLayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoveLayerActionPerformed

    private void jButtonAddNeuron1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNeuron1ActionPerformed
        // TODO add your handling code here:

        net.LayerList.get(Integer.valueOf(jTextAddNeuronLayer.getText())).layerNeurons.remove(0);
        jpanelNeuron1.first=true;
        jpanelNeuron1.repaint();
    }//GEN-LAST:event_jButtonAddNeuron1ActionPerformed

    private void jpanelNeuron1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelNeuron1MouseClicked
        // TODO add your handling code here:
        jTextAddNeuronLayer.setText(String.valueOf(jpanelNeuron1.layerSelected));
    }//GEN-LAST:event_jpanelNeuron1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private NeuralNet.Annealing annealing;
    private NeuralNet.BackPropagation backProp;
    private javax.swing.ButtonGroup buttonGroup1;
    private NeuralNet.Data data;
    private NeuralNet.Func func;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAddLayer;
    private javax.swing.JButton jButtonAddNeuron;
    private javax.swing.JButton jButtonAddNeuron1;
    private javax.swing.JButton jButtonAddSample;
    private javax.swing.JButton jButtonCreateNet;
    private javax.swing.JButton jButtonDataSave;
    private javax.swing.JButton jButtonLoadNet;
    private javax.swing.JButton jButtonRemoveLayer;
    private javax.swing.JButton jButtonSaveNEt;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JCheckBox jCheckBoxRandom;
    private javax.swing.JCheckBox jCheckBoxShuffle;
    private NeuralNet.JDataPanel jDataPanel1;
    private NeuralNet.JFunctionPanel jFunctionPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDError;
    private javax.swing.JLabel jLabelDErrorRms;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelErrorCorrection;
    private javax.swing.JLabel jLabelErrorRms;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2BackProp;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelAlgorythms;
    private javax.swing.JPanel jPanelAnnealing;
    private javax.swing.JPanel jPanelData;
    private javax.swing.JPanel jPanelFunctionGenerator;
    private javax.swing.JPanel jPanelTopology;
    private javax.swing.JPanel jPanelTrainParameters;
    private javax.swing.JRadioButton jRadioButtonAnnealing;
    private javax.swing.JRadioButton jRadioButtonBackprop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSlider jSliderAnnCycles;
    private javax.swing.JSlider jSliderAnnStart;
    private javax.swing.JSlider jSliderAnnStop;
    private javax.swing.JSlider jSliderETA;
    private javax.swing.JSlider jSliderErrorCorrection;
    private javax.swing.JSlider jSliderFeddRandom;
    private javax.swing.JSlider jSliderMOMENTUM;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTexETA;
    private javax.swing.JTextField jTexEpochs;
    private javax.swing.JTextField jTexTopology;
    private javax.swing.JTextField jTextAddNeuronLayer;
    private javax.swing.JTextField jTextAnnCycles;
    private javax.swing.JTextField jTextAnnStart;
    private javax.swing.JTextField jTextAnnStop;
    private javax.swing.JTextField jTextErrorTrackLenght;
    private javax.swing.JTextField jTextFeedRandom;
    private javax.swing.JTextField jTextFieldFormula;
    private javax.swing.JTextField jTextFieldSamples;
    private javax.swing.JTextField jTextMinimumError;
    private javax.swing.JTextField jTextMomentum;
    private javax.swing.JTextField jTextTimerDelay;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private NeuralNet.JTrainHistoryPanel jTrainHistoryPanel1;
    private NeuralNet.JpanelNeuron jpanelNeuron1;
    private NeuralNet.Net net;
    private NeuralNet.TableDataModel tableDataModel1;
    private NeuralNet.Timer timer;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
