/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NeuralNet;

import java.awt.FileDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author faiva78
 */
public class ManagerForm extends javax.swing.JFrame {

    private int epoch = 0;
    private boolean runSimFlag = true;
    public String fileLocation;
    public String extNet = ".net";
    public String extCsv = ".csv";
    public String dir = System.getProperty("user.home");
    public String file = "TestNet0";

    /**
     * Creates new form ManagerForm
     */
    public ManagerForm() {
        initComponents();
        buttonGroup1.add(jRadioButtonBackprop);
        buttonGroup1.add(jRadioButtonAnnealing);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        data = new NeuralNet.Data();
        net = new NeuralNet.Net();
        func = new NeuralNet.Func();
        timer = new NeuralNet.Timer();
        backPropagation = new NeuralNet.BackPropagation();
        buttonGroup1 = new javax.swing.ButtonGroup();
        annealing = new NeuralNet.Annealing();
        jPanelFunctionGenerator = new javax.swing.JPanel();
        jTextFieldFormula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSamples = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jFunctionPanel1 = new NeuralNet.JFunctionPanel();
        jPanelData = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButtonDataSave = new javax.swing.JButton();
        jPanelTrainParameters = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTexEpochs = new javax.swing.JTextField();
        jButtonStart = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextTimerDelay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextMinimumError = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextErrorTrackLenght = new javax.swing.JTextField();
        jPanelTopology = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTexTopology = new javax.swing.JTextField();
        jButtonCreateNet = new javax.swing.JButton();
        jButtonLoadNet = new javax.swing.JButton();
        jButtonSaveNEt = new javax.swing.JButton();
        jPanelAlgorythms = new javax.swing.JPanel();
        jPanel2BackProp = new javax.swing.JPanel();
        jRadioButtonBackprop = new javax.swing.JRadioButton();
        jSliderETA = new javax.swing.JSlider();
        jSliderMOMENTUM = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTexETA = new javax.swing.JTextField();
        jTextMomentum = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabelErrorRms = new javax.swing.JLabel();
        jPanelAnnealing = new javax.swing.JPanel();
        jRadioButtonAnnealing = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSliderAnnStart = new javax.swing.JSlider();
        jSliderAnnStop = new javax.swing.JSlider();
        jSliderAnnCycles = new javax.swing.JSlider();
        jTextAnnStart = new javax.swing.JTextField();
        jTextAnnStop = new javax.swing.JTextField();
        jTextAnnCycles = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTrainHistoryPanel = new NeuralNet.JTrainHistoryPanel();
        jPanel2 = new javax.swing.JPanel();
        jDataPanel1 = new NeuralNet.JDataPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFunctionGenerator.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Function Data Generator"));

        jTextFieldFormula.setText("(sin((2*x)*3.1416)+1)/2");

        jLabel2.setText("Samples");

        jTextFieldSamples.setText("30");

        jButton1.setText("test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestFuncActionPerformed(evt);
            }
        });

        jFunctionPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jFunctionPanel1Layout = new javax.swing.GroupLayout(jFunctionPanel1);
        jFunctionPanel1.setLayout(jFunctionPanel1Layout);
        jFunctionPanel1Layout.setHorizontalGroup(
            jFunctionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jFunctionPanel1Layout.setVerticalGroup(
            jFunctionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelFunctionGeneratorLayout = new javax.swing.GroupLayout(jPanelFunctionGenerator);
        jPanelFunctionGenerator.setLayout(jPanelFunctionGeneratorLayout);
        jPanelFunctionGeneratorLayout.setHorizontalGroup(
            jPanelFunctionGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFunctionGeneratorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFunctionGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFunctionGeneratorLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jTextFieldSamples, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextFieldFormula, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFunctionGeneratorLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jFunctionPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFunctionGeneratorLayout.setVerticalGroup(
            jPanelFunctionGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFunctionGeneratorLayout.createSequentialGroup()
                .addComponent(jTextFieldFormula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFunctionGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldSamples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFunctionPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelData.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data"));

        jButton2.setText("Function");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateDataActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "inputs", "test", "output"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Load");
        jButton3.setEnabled(false);

        jButtonDataSave.setText("save");
        jButtonDataSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDataSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDataLayout = new javax.swing.GroupLayout(jPanelData);
        jPanelData.setLayout(jPanelDataLayout);
        jPanelDataLayout.setHorizontalGroup(
            jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataLayout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDataSave, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanelDataLayout.setVerticalGroup(
            jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataLayout.createSequentialGroup()
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButtonDataSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
        );

        jPanelTrainParameters.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Simulation Parameters"));

        jLabel3.setText("Epochs");

        jTexEpochs.setText("25000");

        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jButtonStop.setText("Stop");
        jButtonStop.setEnabled(false);
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });

        jLabel4.setText("Delay (ms)");

        jTextTimerDelay.setText("200");

        jLabel6.setText("Min Error");

        jTextMinimumError.setText("0.01");

        jLabel7.setText("Rms Len");

        jTextErrorTrackLenght.setText("2500");

        javax.swing.GroupLayout jPanelTrainParametersLayout = new javax.swing.GroupLayout(jPanelTrainParameters);
        jPanelTrainParameters.setLayout(jPanelTrainParametersLayout);
        jPanelTrainParametersLayout.setHorizontalGroup(
            jPanelTrainParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrainParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTrainParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTrainParametersLayout.createSequentialGroup()
                        .addComponent(jButtonStop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(jButtonStart)
                        .addContainerGap())
                    .addGroup(jPanelTrainParametersLayout.createSequentialGroup()
                        .addGroup(jPanelTrainParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelTrainParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextMinimumError, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTexEpochs, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextTimerDelay, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextErrorTrackLenght, javax.swing.GroupLayout.Alignment.LEADING)))))
        );
        jPanelTrainParametersLayout.setVerticalGroup(
            jPanelTrainParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrainParametersLayout.createSequentialGroup()
                .addGroup(jPanelTrainParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTexEpochs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTrainParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextTimerDelay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTrainParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextMinimumError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTrainParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextErrorTrackLenght, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTrainParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStop)
                    .addComponent(jButtonStart))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTopology.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Net"));

        jLabel5.setText("Topology");

        jTexTopology.setText("1,7,1");

        jButtonCreateNet.setText("New");
        jButtonCreateNet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateNetActionPerformed(evt);
            }
        });

        jButtonLoadNet.setText("Load");
        jButtonLoadNet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadNetActionPerformed(evt);
            }
        });

        jButtonSaveNEt.setText("Save");
        jButtonSaveNEt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveNEtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopologyLayout = new javax.swing.GroupLayout(jPanelTopology);
        jPanelTopology.setLayout(jPanelTopologyLayout);
        jPanelTopologyLayout.setHorizontalGroup(
            jPanelTopologyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopologyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTexTopology))
            .addGroup(jPanelTopologyLayout.createSequentialGroup()
                .addGroup(jPanelTopologyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSaveNEt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLoadNet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCreateNet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTopologyLayout.setVerticalGroup(
            jPanelTopologyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopologyLayout.createSequentialGroup()
                .addGroup(jPanelTopologyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTexTopology, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCreateNet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLoadNet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSaveNEt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAlgorythms.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Training algorythm parameters"));

        jPanel2BackProp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jRadioButtonBackprop.setSelected(true);
        jRadioButtonBackprop.setText("Backpropagation");

        jSliderETA.setValue(23);

        jSliderMOMENTUM.setValue(8);

        jLabel9.setText("Momentum");

        jLabel8.setText("ETA");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSliderETA, org.jdesktop.beansbinding.ELProperty.create("${(value*value)/500}"), jTexETA, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSliderMOMENTUM, org.jdesktop.beansbinding.ELProperty.create("${(value*value)/500}"), jTextMomentum, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel13.setText("Error (rms)");

        jLabelErrorRms.setText("0");

        javax.swing.GroupLayout jPanel2BackPropLayout = new javax.swing.GroupLayout(jPanel2BackProp);
        jPanel2BackProp.setLayout(jPanel2BackPropLayout);
        jPanel2BackPropLayout.setHorizontalGroup(
            jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2BackPropLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2BackPropLayout.createSequentialGroup()
                        .addGroup(jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2BackPropLayout.createSequentialGroup()
                                .addComponent(jTextMomentum, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSliderMOMENTUM, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2BackPropLayout.createSequentialGroup()
                                .addComponent(jTexETA, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSliderETA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2BackPropLayout.createSequentialGroup()
                        .addComponent(jRadioButtonBackprop)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelErrorRms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2BackPropLayout.setVerticalGroup(
            jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2BackPropLayout.createSequentialGroup()
                .addGroup(jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonBackprop, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabelErrorRms))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTexETA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(jSliderETA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2BackPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextMomentum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(jSliderMOMENTUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelAnnealing.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jRadioButtonAnnealing.setText("Annealing");
        jRadioButtonAnnealing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAnnealingActionPerformed(evt);
            }
        });

        jLabel10.setText("Stop");

        jLabel11.setText("Start");

        jLabel12.setText("Cycles");

        jSliderAnnStart.setValue(100);

        jSliderAnnStop.setValue(1);

        jSliderAnnCycles.setValue(30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSliderAnnStart, org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextAnnStart, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSliderAnnStop, org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextAnnStop, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSliderAnnCycles, org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextAnnCycles, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanelAnnealingLayout = new javax.swing.GroupLayout(jPanelAnnealing);
        jPanelAnnealing.setLayout(jPanelAnnealingLayout);
        jPanelAnnealingLayout.setHorizontalGroup(
            jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnnealingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextAnnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextAnnCycles, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextAnnStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSliderAnnStop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jSliderAnnCycles, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSliderAnnStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelAnnealingLayout.createSequentialGroup()
                .addComponent(jRadioButtonAnnealing)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelAnnealingLayout.setVerticalGroup(
            jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnnealingLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderAnnCycles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAnnealingLayout.createSequentialGroup()
                        .addComponent(jRadioButtonAnnealing, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAnnealingLayout.createSequentialGroup()
                                .addGroup(jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextAnnStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextAnnStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelAnnealingLayout.createSequentialGroup()
                                .addComponent(jSliderAnnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSliderAnnStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAnnealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextAnnCycles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelAlgorythmsLayout = new javax.swing.GroupLayout(jPanelAlgorythms);
        jPanelAlgorythms.setLayout(jPanelAlgorythmsLayout);
        jPanelAlgorythmsLayout.setHorizontalGroup(
            jPanelAlgorythmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlgorythmsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlgorythmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelAnnealing, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2BackProp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAlgorythmsLayout.setVerticalGroup(
            jPanelAlgorythmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlgorythmsLayout.createSequentialGroup()
                .addComponent(jPanel2BackProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelAnnealing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "History"));

        jTrainHistoryPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jTrainHistoryPanelLayout = new javax.swing.GroupLayout(jTrainHistoryPanel);
        jTrainHistoryPanel.setLayout(jTrainHistoryPanelLayout);
        jTrainHistoryPanelLayout.setHorizontalGroup(
            jTrainHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jTrainHistoryPanelLayout.setVerticalGroup(
            jTrainHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTrainHistoryPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTrainHistoryPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data "));

        jDataPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jDataPanel1Layout = new javax.swing.GroupLayout(jDataPanel1);
        jDataPanel1.setLayout(jDataPanel1Layout);
        jDataPanel1Layout.setHorizontalGroup(
            jDataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDataPanel1Layout.setVerticalGroup(
            jDataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDataPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDataPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelFunctionGenerator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTopology, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelTrainParameters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelAlgorythms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelFunctionGenerator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelTopology, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelTrainParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jPanelAlgorythms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTestFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestFuncActionPerformed
        // Paint function:
        func = new Func(jTextFieldFormula.getText());
        int steps = Integer.valueOf(jTextFieldSamples.getText());
        jFunctionPanel1.func = func;
        jFunctionPanel1.steps = steps;
        jFunctionPanel1.repaint();
    }//GEN-LAST:event_jButtonTestFuncActionPerformed

    private void jButtonCreateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateDataActionPerformed
        // Create table

        //data = new Data();
        func = new Func(jTextFieldFormula.getText());
        double steps = 1 / (Double.valueOf(jTextFieldSamples.getText()));

        Uti.DataFunc1P(func, 0, 1, steps, data);

        String[] col = new String[]{"Input", "Test", "Output"};

        int siz = data.SampleList.size();
        Object[][] dat = new Object[siz][];

        for (int i = 0; i < data.SampleList.size(); i++) {
            Data.Sample sample = data.SampleList.get(i);

            String a = Uti.ArrayToString(Uti.DoubleArrayToString(sample.inputData));
            String b = Uti.ArrayToString(Uti.DoubleArrayToString(sample.testData));
            String c = Uti.ArrayToString(Uti.DoubleArrayToString(sample.outputData));
            dat[i] = new String[]{a, b, c};
        }

        jTable1.setModel(new DefaultTableModel(dat, col));
    }//GEN-LAST:event_jButtonCreateDataActionPerformed

    private void jButtonCreateNetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateNetActionPerformed
        // Create a New Net
        net = new Net();
        net.createNet(jTexTopology.getText());

    }//GEN-LAST:event_jButtonCreateNetActionPerformed

    private void updateTrain() {

        // set backprop parameters
        backPropagation.ETA = Double.valueOf(jTexETA.getText());
        backPropagation.MOMENTUM = Double.valueOf(jTextMomentum.getText());
        
       //annealing.start;

    }


    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed

        Thread RunSim = new Thread(new Runnable() {

            @Override
            public void run() {
                try {

                    //set up buttons visibility
                    jButtonStop.setEnabled(true);
                    jButtonStart.setEnabled(false);

                    // set timer
                    timer.setTimeOut(Long.valueOf(jTextTimerDelay.getText()));

                    // set tracking error lenght
                    data.errorTrack.lenght = Integer.valueOf(jTextErrorTrackLenght.getText());

                    // set the History panel parameters
                    jTrainHistoryPanel.minimumError = Double.valueOf(jTextMinimumError.getText());
                    jTrainHistoryPanel.totalEpoch = Integer.valueOf(jTexEpochs.getText());
                    jTrainHistoryPanel.data = data;
                    jTrainHistoryPanel.clear();

                    //set the data panel
                    jDataPanel1.data = data;

                    updateTrain();
                    
                    
                    // set sto flag
                    runSimFlag = true;

                    // reset eèpoch
                    epoch = 0;

                    while (runSimFlag) {

                        while (epoch < Long.valueOf(jTexEpochs.getText())) {

                            //increase epoch
                            epoch++;

                            //train 
                            if (jRadioButtonBackprop.isSelected()) {
                                backPropagation.train(net, data);
                            }

                            if (jRadioButtonAnnealing.isSelected()) {
                                annealing.train(net, data);
                            }

                            // record error
                            data.errorTrack.add(data.getDataError());

                            // if timer
                            if (timer.check()) {

                                // print error
                                String sd = String.format("%f", data.errorTrack.mean());
                                jLabelErrorRms.setText(sd);

                                //update and paint panels
                                jTrainHistoryPanel.epoch = epoch;
                                jTrainHistoryPanel.repaint();
                                jDataPanel1.repaint();

                                updateTrain();

                                // reset timer
                                timer.reset();

                            }

                            // if solution found
                            boolean err = (data.errorTrack.mean() < Double.valueOf(jTextMinimumError.getText()));
                            if (err) {
                                runSimFlag = false;

                            }

                            //if end of sim
                            if (!runSimFlag) {
                                jButtonStop.setEnabled(false);
                                jButtonStart.setEnabled(true);
                                System.out.println("finished ");
                                break;
                            }

                        }
                        //clear and reset epoch 
                        epoch = 0;
                        jTrainHistoryPanel.clear();

                    }

                } catch (Exception e) {
                }

            }
        });
        //start te thread
        RunSim.start();

    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed

        jButtonStop.setEnabled(false);
        jButtonStart.setEnabled(true);
        runSimFlag = false;
    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jRadioButtonAnnealingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAnnealingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAnnealingActionPerformed

    private void jButtonLoadNetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadNetActionPerformed
  
       
        //String fileLocation = "C:\\Users\\alessia/TestNet0.net";
        FileDialog fd = new FileDialog(this, "Load a net", FileDialog.LOAD);
        fd.setDirectory(dir);
        fd.setFile("*.net");
        fd.setVisible(true);
        String filename = fd.getFile();
        if (filename != null) {
             net = new Net();
            Uti.loadNet(dir + "/" + filename, net);
        }
    }//GEN-LAST:event_jButtonLoadNetActionPerformed

    private void jButtonSaveNEtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveNEtActionPerformed
        
        //String fileLocation = "C:\\Users\\alessia/TestNet0.net";
        FileDialog fd = new FileDialog(this, "Save a net", FileDialog.SAVE);
        fd.setDirectory(dir);
        fd.setFile("*.net");
        fd.setVisible(true);
        String filename = fd.getFile();
        if (filename != null) {
            Uti.saveNet(dir + "/" + filename + extNet, net);
        }

    }//GEN-LAST:event_jButtonSaveNEtActionPerformed

    private void jButtonDataSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDataSaveActionPerformed
        // TODO add your handling code here:
       
        FileDialog fd = new FileDialog(this, "Save net data", FileDialog.SAVE);
        fd.setDirectory(dir);
        fd.setFile("*.csv");
        fd.setVisible(true);
        String filename = fd.getFile();
        if (filename != null) {
            Uti.saveDataCSV(net,data,dir + "/" + filename + extCsv);
        }
        //Uti.saveDataCSV(net, data, dir + file + extCsv);


    }//GEN-LAST:event_jButtonDataSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private NeuralNet.Annealing annealing;
    private NeuralNet.BackPropagation backPropagation;
    private javax.swing.ButtonGroup buttonGroup1;
    private NeuralNet.Data data;
    private NeuralNet.Func func;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonCreateNet;
    private javax.swing.JButton jButtonDataSave;
    private javax.swing.JButton jButtonLoadNet;
    private javax.swing.JButton jButtonSaveNEt;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStop;
    private NeuralNet.JDataPanel jDataPanel1;
    private NeuralNet.JFunctionPanel jFunctionPanel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelErrorRms;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2BackProp;
    private javax.swing.JPanel jPanelAlgorythms;
    private javax.swing.JPanel jPanelAnnealing;
    private javax.swing.JPanel jPanelData;
    private javax.swing.JPanel jPanelFunctionGenerator;
    private javax.swing.JPanel jPanelTopology;
    private javax.swing.JPanel jPanelTrainParameters;
    private javax.swing.JRadioButton jRadioButtonAnnealing;
    private javax.swing.JRadioButton jRadioButtonBackprop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSliderAnnCycles;
    private javax.swing.JSlider jSliderAnnStart;
    private javax.swing.JSlider jSliderAnnStop;
    private javax.swing.JSlider jSliderETA;
    private javax.swing.JSlider jSliderMOMENTUM;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTexETA;
    private javax.swing.JTextField jTexEpochs;
    private javax.swing.JTextField jTexTopology;
    private javax.swing.JTextField jTextAnnCycles;
    private javax.swing.JTextField jTextAnnStart;
    private javax.swing.JTextField jTextAnnStop;
    private javax.swing.JTextField jTextErrorTrackLenght;
    private javax.swing.JTextField jTextFieldFormula;
    private javax.swing.JTextField jTextFieldSamples;
    private javax.swing.JTextField jTextMinimumError;
    private javax.swing.JTextField jTextMomentum;
    private javax.swing.JTextField jTextTimerDelay;
    private NeuralNet.JTrainHistoryPanel jTrainHistoryPanel;
    private NeuralNet.Net net;
    private NeuralNet.Timer timer;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
